spring:
  application:
    name: proxysql-ha

  jpa:
    hibernate:
      ddl-auto: update
  datasource:
    url: jdbc:mysql://127.0.0.1:16033/testdb?characterEncoding=UTF-8&serverTimezone=UTC
    username: root
    password: root