### Send POST request with json body
POST localhost:8080/api/post
Content-Type: application/json

{
  "userId": 2,
  "contents": "asd"
}

###
DELETE 0.0.0.0:8080/api/post
Content-Type: application/json

[1]
