version: '3.0'

services:
  orchestrator:
    image: openarkcode/orchestrator
    container_name: orchestrator
    hostname: orchestrator
    networks:
      mysql_mybridge:
        aliases:
          - orchestrator
    ports:
      - "3000:3000"
    volumes:
      - ./etc/orchestrator.conf.json:/etc/orchestrator.conf.json

networks:
  mysql_mybridge:
    external: true