version: '3'

services:
  proxysql:
    image: proxysql/proxysql
    container_name: proxysql
    hostname: proxysql
    networks:
      mysql_mybridge:
        aliases:
          - proxysql
    ports:
      - "16032:6032"
      - "16033:6033"
    volumes:
      - ./data:/var/lib/proxysql
      - ./conf/proxysql.cnf:/etc/proxysql.cnf

networks:
  mysql_mybridge:
    external: true
